# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest




    # steps represent sequence task
    steps:
    - uses: actions/checkout@v2
    - name: Run make command
      run: make hello
