name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # thet type of runner
    runs-on: ubuntu-latest
    # steps represent sequence task
    steps:
    - uses: actions/checkout@v2
    - name: Run make command
      run: make hello
