name: CI

on:
  push:

jobs:
  build:
    # thet type of runner
    runs-on: ubuntu-latest
    # steps represent sequence task
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: install depedencies
      run: |
       make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with python
      run: |
        make test
    
    
    
    - name: Run make command
      run: make hello
